export const datas = [
  {
    id: "1",
    BranchId: "1",
    CategoryId: "clothing",
    OriginId: "1",
    ProductName: "Áo sơ mi nam hàng hiệu",
    ProductPrice: 1000000,
    ProductQuantity: 100,
    ProductDescription:
      "Áo sơ mi nam cao cấp, chất liệu cotton cao cấp, thoáng mát, phù hợp cho các dịp trang trọng.",
    ProductMaterial: "100% cotton",
    Views: 500,
    Comment: 50,
    Rate: 4.5,
    ProductType: "Thời trang nam",
    ProductSold: 80,
    ListFileImg: ["shirt1.jpg", "shirt2.jpg"],
  },
  {
    id: "2",
    BranchId: "2",
    CategoryId: "footwear",
    OriginId: "2",
    ProductName: "Giày thể thao nam Adidas Ultra Boost",
    ProductPrice: 2500000,
    ProductQuantity: 50,
    ProductDescription:
      "Giày thể thao nam hàng hiệu, thiết kế thời trang, êm ái, giảm chấn cho các hoạt động thể thao.",
    ProductMaterial: "Da tổng hợp, lưới thoáng khí",
    Views: 800,
    Comment: 70,
    Rate: 4.8,
    ProductType: "Thể thao nam",
    ProductSold: 40,
    ListFileImg: ["shoe1.jpg", "shoe2.jpg"],
  },
  {
    id: "3",
    BranchId: "3",
    CategoryId: "accessories",
    OriginId: "2",
    ProductName: "Đồng hồ nữ Michael Kors MK5865",
    ProductPrice: 4500000,
    ProductQuantity: 30,
    ProductDescription:
      "Đồng hồ nữ hàng hiệu, kiểu dáng sang trọng, chất liệu cao cấp, phù hợp cho mọi dịp.",
    ProductMaterial: "Thép không gỉ, kính cứng",
    Views: 300,
    Comment: 25,
    Rate: 4.7,
    ProductType: "Phụ kiện nữ",
    ProductSold: 20,
    ListFileImg: ["watch1.jpg", "watch2.jpg"],
  },
  {
    id: "4",
    BranchId: "2",
    CategoryId: "clothing",
    OriginId: "1",
    ProductName: "Áo khoác dù nam North Face",
    ProductPrice: 3500000,
    ProductQuantity: 40,
    ProductDescription:
      "Áo khoác dù nam chất lượng cao, chống nước, giữ ấm tốt trong mùa đông, thiết kế hiện đại.",
    ProductMaterial: "Vải dù, lớp lót nỉ",
    Views: 600,
    Comment: 45,
    Rate: 4.6,
    ProductType: "Thời trang nam",
    ProductSold: 35,
    ListFileImg: ["jacket1.jpg", "jacket2.jpg"],
  },
  {
    id: "5",
    BranchId: "1",
    CategoryId: "accessories",
    OriginId: "2",
    ProductName: "Ví nam da bò thật Tommy Hilfiger",
    ProductPrice: 1200000,
    ProductQuantity: 60,
    ProductDescription:
      "Ví nam da bò thật, thiết kế đơn giản, sang trọng, tiện dụng.",
    ProductMaterial: "Da bò",
    Views: 400,
    Comment: 35,
    Rate: 4.6,
    ProductType: "Phụ kiện nam",
    ProductSold: 50,
    ListFileImg: ["wallet1.jpg", "wallet2.jpg"],
  },
];

export const brands = [
  { id: "1", name: "Brand A" },
  { id: "2", name: "Brand B" },
  { id: "3", name: "Brand C" },
];

export const originData = [
  { id: "1", name: "Origin A" },
  { id: "2", name: "Origin B" },
  { id: "3", name: "Origin C" },
];
